# -*- mode: ruby -*-
# vim: set ft=ruby :

BOX_NAME = "generic/debian10";

IP_NET = "192.168.50";
NET_MASK_24 = "255.255.255.0";
IP_ZBX5_DB  = IP_NET + ".10";
IP_ZBX5_SRV = IP_NET + ".20";
IP_ZBX5_WEB = IP_NET + ".30";

VB_PREFIX = "otus-monlog-les03-";
VB_NET_A = VB_PREFIX + "intnet-A";

HOSTS = {

    :"zbx5-db" => {
        :box_name => BOX_NAME,
        :cpu => '1',
        :ram => "512",
        :net => [
            {adapter: 2, ip: IP_ZBX5_DB, netmask: NET_MASK_24, virtualbox__intnet: VB_NET_A},
        ],
        :port => []
    },

    :"zbx5-srv" => {
        :box_name => BOX_NAME,
        :cpu => '1',
        :ram => "512",
        :net => [
            {adapter: 2, ip: IP_ZBX5_SRV, netmask: NET_MASK_24, virtualbox__intnet: VB_NET_A},
        ],
        :port => []
    },

    :"zbx5-web" => {
        :box_name => BOX_NAME,
        :cpu => '1',
        :ram => "512",
        :net => [
            {adapter: 2, ip: IP_ZBX5_WEB, netmask: NET_MASK_24, virtualbox__intnet: VB_NET_A},
        ],
        :port => [
            {guest: 80, host: 8080},
            {guest: 443, host: 8081}
        ]
    }

}

Vagrant.configure("2") do |config|

    HOSTS.each do |boxname, boxconfig|

        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s

            boxconfig[:net].each do |ipconf|
                box.vm.network "private_network", ipconf
            end
            boxconfig[:port].each do |portconf|
                box.vm.network "forwarded_port", portconf
            end

            box.vm.provider :virtualbox do |vb|
                vb.cpus = boxconfig[:cpu]
                vb.memory = boxconfig[:ram]
                vb.name = VB_PREFIX + "%s" % boxname
            end

            box.vm.provision "shell", path: "provision.sh"

            #box.vm.provision "shell", run: "always", inline: <<-SHELL
            #SHELL

        end
    end
end
