---
- name: Первичная подготовка виртуальных машин
  hosts: zbx5
  become: True
  tasks:
    - name: Обновление машины
      apt: >
        update_cache=yes
        upgrade=dist
        force_apt_get=yes
        cache_valid_time=3600

    - name: Установка часового пояса
      timezone:
        name: Europe/Moscow
