---
- name: Configure webserver with nginx
  hosts: zbx5
  become: True
  tasks:
    - name: install nginx
      apt: >
        name=nginx
        update_cache=yes

    - name: copy nginx config file
      copy: >
        src=../files/nginx.conf
        dest=/etc/nginx/sites-available/default

    - name: enable configuration
      file: >
        src=/etc/nginx/sites-available/default
        dest=/etc/nginx/sites-enabled/default

    - name: copy index.html
      template: >
        src=../templates/index.html.j2
        dest=/usr/share/nginx/html/index.html
        mode=0644

    - name: restart nginx
      service: >
        name=nginx
        state=restarted

- name: Install RDBMS MariaDB
  hosts: zbx5-db
  become: True
  tasks:
    - name: install mariadb
      apt: >
        name=mariadb-server
        update_cache=yes
